openapi: "3.0.3"

info:
  title: "Device Manager API"
  version: "1.0.0"
  description: "API contract for the device-manager service. Manages device CRUD, status queries, and lifecycle operations."
  x-accord-status: draft
  x-accord-scanned: "2026-02-10T00:00:00Z"

paths:
  /api/devices:
    get:
      summary: "List all devices"
      operationId: listDevices
      parameters:
        - name: status
          in: query
          required: false
          schema:
            type: string
            enum: [ONLINE, OFFLINE, MAINTENANCE, UNKNOWN]
          description: "Filter by device status"
        - name: page
          in: query
          required: false
          schema:
            type: integer
            default: 0
          description: "Page number (zero-based)"
        - name: size
          in: query
          required: false
          schema:
            type: integer
            default: 20
          description: "Page size"
      responses:
        '200':
          description: "List of devices"
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Device'
    post:
      summary: "Create a new device"
      operationId: createDevice
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateDeviceRequest'
      responses:
        '201':
          description: "Device created"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Device'
        '400':
          description: "Invalid input"

  /api/devices/{id}:
    get:
      summary: "Get device by ID"
      operationId: getDeviceById
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
          description: "Unique device identifier"
      responses:
        '200':
          description: "Device details"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Device'
        '404':
          description: "Device not found"

  /api/devices/{id}/reboot:
    post:
      summary: "Reboot a device"
      operationId: rebootDevice
      x-accord-status: proposed
      x-accord-request: req-002-reboot-device
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
          description: "Unique device identifier"
      responses:
        '202':
          description: "Reboot initiated"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RebootResponse'
        '404':
          description: "Device not found"
        '409':
          description: "Device not in a rebootable state"

components:
  schemas:
    Device:
      type: object
      properties:
        id:
          type: string
          description: "Unique device identifier"
        name:
          type: string
          description: "Device display name"
        ipAddress:
          type: string
          description: "Device IP address"
        macAddress:
          type: string
          description: "Device MAC address"
        status:
          $ref: '#/components/schemas/DeviceStatus'
        lastSeen:
          type: string
          format: date-time
          description: "Last seen timestamp"
      required:
        - id
        - name
        - status

    DeviceStatus:
      type: string
      enum: [ONLINE, OFFLINE, MAINTENANCE, UNKNOWN]
      description: "Current device status"

    CreateDeviceRequest:
      type: object
      properties:
        name:
          type: string
          description: "Device display name"
        ipAddress:
          type: string
          description: "Device IP address"
        macAddress:
          type: string
          description: "Device MAC address"
      required:
        - name

    RebootResponse:
      type: object
      properties:
        deviceId:
          type: string
        status:
          type: string
          description: "Reboot status (e.g. INITIATED)"
        message:
          type: string
