openapi: "3.0.3"

info:
  title: "frontend API"
  version: "0.1.0"
  description: >
    API contract for the frontend service.
    Serves page data by consuming web-server APIs and composing them into page views.
  x-accord-status: draft
  x-accord-scanned: "2026-02-10T00:00:00Z"

paths:
  /api/pages/dashboard:
    get:
      summary: "Get dashboard page data"
      operationId: getDashboardPage
      description: >
        Returns a PageData object containing dashboard statistics and recent devices.
        Internally aggregates data from web-server /api/dashboard/stats and /api/dashboard/devices.
      responses:
        '200':
          description: "Successful response with dashboard page data"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PageData'

  /api/pages/devices:
    get:
      summary: "Get devices page data"
      operationId: getDevicesPage
      description: >
        Returns a PageData object containing the list of devices.
        Internally fetches data from web-server /api/dashboard/devices.
      responses:
        '200':
          description: "Successful response with devices page data"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PageData'

components:
  schemas:
    PageData:
      type: object
      description: "Generic page data wrapper returned by all page endpoints"
      properties:
        title:
          type: string
          description: "Page title (e.g. 'Dashboard', 'Devices')"
        data:
          description: "Page-specific data payload (structure varies by endpoint)"
        timestamp:
          type: string
          format: date-time
          description: "ISO 8601 timestamp of when the page data was generated"
      required:
        - title
        - timestamp
