openapi: "3.0.3"

info:
  title: "frontend API"
  version: "0.2.0"
  description: >
    API contract for the frontend service.
    Serves page data by consuming web-server APIs and composing them into page views.
  x-accord-status: draft
  x-accord-scanned: "2026-02-10T00:00:00Z"

paths:
  /api/pages/dashboard:
    get:
      summary: "Get dashboard page data"
      operationId: getDashboardPage
      description: >
        Returns a PageData object containing dashboard statistics and recent devices.
        Internally aggregates data from web-server /api/dashboard/stats and /api/dashboard/devices.
      responses:
        '200':
          description: "Successful response with dashboard page data"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PageData'

  /api/pages/devices:
    get:
      summary: "Get paginated devices page data"
      operationId: getDevicesPage
      description: >
        Returns a PageData object containing a paginated list of devices with
        filtering, search, and sorting support. Internally proxies to
        web-server /api/proxy/devices (falls back to mock data if unavailable).
      parameters:
        - name: page
          in: query
          required: false
          schema:
            type: integer
            default: 0
          description: "Zero-based page index"
        - name: size
          in: query
          required: false
          schema:
            type: integer
            default: 20
          description: "Number of items per page"
        - name: status
          in: query
          required: false
          schema:
            $ref: '#/components/schemas/DeviceStatus'
          description: "Filter by device status"
        - name: name
          in: query
          required: false
          schema:
            type: string
          description: "Search by device name (case-insensitive contains)"
        - name: sort
          in: query
          required: false
          schema:
            type: string
            default: "name"
            enum: ["name", "lastSeen", "status"]
          description: "Field to sort by"
        - name: direction
          in: query
          required: false
          schema:
            type: string
            default: "asc"
            enum: ["asc", "desc"]
          description: "Sort direction"
      responses:
        '200':
          description: "Successful response with paginated devices page data"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PageData'

components:
  schemas:
    PageData:
      type: object
      description: "Generic page data wrapper returned by all page endpoints"
      properties:
        title:
          type: string
          description: "Page title (e.g. 'Dashboard', 'Devices')"
        data:
          description: "Page-specific data payload (structure varies by endpoint)"
        timestamp:
          type: string
          format: date-time
          description: "ISO 8601 timestamp of when the page data was generated"
      required:
        - title
        - timestamp

    DeviceStatus:
      type: string
      description: "Status of a device"
      enum:
        - ONLINE
        - OFFLINE
        - MAINTENANCE
        - UNKNOWN

    Device:
      type: object
      description: "Device representation"
      properties:
        id:
          type: string
        name:
          type: string
        ipAddress:
          type: string
        macAddress:
          type: string
        status:
          $ref: '#/components/schemas/DeviceStatus'
        lastSeen:
          type: string
          format: date-time
      required:
        - id
        - name
        - status

    PaginatedDeviceResponse:
      type: object
      description: "Paginated wrapper for device lists"
      properties:
        content:
          type: array
          items:
            $ref: '#/components/schemas/Device'
        page:
          type: integer
        size:
          type: integer
        totalElements:
          type: integer
          format: int64
        totalPages:
          type: integer
        first:
          type: boolean
        last:
          type: boolean
      required:
        - content
        - page
        - size
        - totalElements
        - totalPages
