openapi: "3.0.3"

info:
  title: "web-server API"
  version: "0.1.0"
  description: >
    BFF layer — aggregates device-manager data, provides dashboard statistics
    and device proxy APIs.
  x-accord-status: draft
  x-accord-scanned: "2026-02-10T00:00:00Z"

servers:
  - url: http://localhost:8080
    description: Local development

paths:
  /api/dashboard/stats:
    get:
      summary: "Get dashboard statistics"
      description: >
        Returns aggregate device statistics including total, online, and offline
        device counts. Data is sourced from the device-manager service.
      operationId: getDashboardStats
      tags:
        - Dashboard
      responses:
        '200':
          description: "Successful response with dashboard statistics"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DashboardStats'

  /api/dashboard/devices:
    get:
      summary: "List all devices for dashboard"
      description: >
        Returns a summary list of all devices, proxied from the device-manager
        service. Used to populate the dashboard device table.
      operationId: getDashboardDevices
      tags:
        - Dashboard
      responses:
        '200':
          description: "Successful response with list of device summaries"
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/DeviceSummary'

  /api/proxy/devices:
    get:
      summary: "List devices with pagination"
      description: >
        Returns a paginated list of devices proxied from device-manager.
        Supports filtering by status, searching by name, and sorting.
      operationId: getDevicesPaginated
      tags:
        - DeviceProxy
      parameters:
        - name: page
          in: query
          required: false
          schema:
            type: integer
            default: 0
          description: "Zero-based page index"
        - name: size
          in: query
          required: false
          schema:
            type: integer
            default: 20
          description: "Number of items per page"
        - name: status
          in: query
          required: false
          schema:
            type: string
            enum: [ONLINE, OFFLINE, MAINTENANCE, UNKNOWN]
          description: "Filter by device status"
        - name: name
          in: query
          required: false
          schema:
            type: string
          description: "Search by device name (case-insensitive contains)"
        - name: sort
          in: query
          required: false
          schema:
            type: string
            default: "name"
            enum: ["name", "lastSeen", "status"]
          description: "Field to sort by"
        - name: direction
          in: query
          required: false
          schema:
            type: string
            default: "asc"
            enum: ["asc", "desc"]
          description: "Sort direction"
      responses:
        '200':
          description: "Paginated list of devices"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PaginatedDeviceResponse'

  /api/proxy/devices/{id}:
    get:
      summary: "Get device by ID (proxy)"
      description: >
        Proxies a request to the device-manager service to retrieve a single
        device by its unique identifier.
      operationId: getDeviceById
      tags:
        - DeviceProxy
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
          description: "Unique identifier of the device"
      responses:
        '200':
          description: "Successful response with device details"
          content:
            application/json:
              schema:
                type: object
                description: "Device object as returned by device-manager (pass-through)"
        '404':
          description: "Device not found"

components:
  schemas:
    DashboardStats:
      type: object
      description: "Aggregate statistics for the device dashboard"
      properties:
        totalDevices:
          type: integer
          description: "Total number of registered devices"
        onlineDevices:
          type: integer
          description: "Number of devices currently online"
        offlineDevices:
          type: integer
          description: "Number of devices currently offline"
        lastUpdated:
          type: string
          format: date-time
          description: "Timestamp of when the stats were computed"
      required:
        - totalDevices
        - onlineDevices
        - offlineDevices
        - lastUpdated

    PaginatedDeviceResponse:
      type: object
      description: "Paginated wrapper for device list responses"
      properties:
        content:
          type: array
          items:
            $ref: '#/components/schemas/DeviceSummary'
        page:
          type: integer
          description: "Current page index (zero-based)"
        size:
          type: integer
          description: "Number of items per page"
        totalElements:
          type: integer
          format: int64
          description: "Total number of matching devices"
        totalPages:
          type: integer
          description: "Total number of pages"
        first:
          type: boolean
          description: "Whether this is the first page"
        last:
          type: boolean
          description: "Whether this is the last page"
      required:
        - content
        - page
        - size
        - totalElements
        - totalPages

    DeviceSummary:
      type: object
      description: "Summary representation of a device"
      properties:
        id:
          type: string
          description: "Unique device identifier"
        name:
          type: string
          description: "Display name of the device"
        status:
          type: string
          description: "Current device status (e.g., ONLINE, OFFLINE)"
          enum:
            - ONLINE
            - OFFLINE
        ipAddress:
          type: string
          description: "IP address of the device"
      required:
        - id
        - name
        - status
        - ipAddress
