openapi: "3.0.3"

info:
  title: "device-manager API"
  version: "0.2.0"
  description: "API contract for the device-manager service. Manages network devices with CRUD operations, filtering, and search."
  x-accord-status: stable
  x-accord-scanned: "2026-02-11T00:00:00Z"

paths:
  /api/devices:
    get:
      summary: "List devices"
      description: "Returns a paginated list of devices with optional filtering by status and name, and configurable sorting."
      operationId: listDevices
      parameters:
        - name: status
          in: query
          required: false
          schema:
            $ref: '#/components/schemas/DeviceStatus'
          description: "Filter by device status"
        - name: name
          in: query
          required: false
          schema:
            type: string
          description: "Filter by device name (case-insensitive partial match)"
        - name: page
          in: query
          required: false
          schema:
            type: integer
            default: 0
          description: "Page number (zero-based)"
        - name: size
          in: query
          required: false
          schema:
            type: integer
            default: 20
          description: "Page size"
        - name: sort
          in: query
          required: false
          schema:
            type: string
            default: "name"
            enum:
              - name
              - status
              - lastSeen
          description: "Sort field"
        - name: direction
          in: query
          required: false
          schema:
            type: string
            default: "asc"
            enum:
              - asc
              - desc
          description: "Sort direction"
      responses:
        '200':
          description: "Paginated list of devices"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PaginatedDeviceResponse'

    post:
      summary: "Create a device"
      description: "Creates a new device. A UUID is assigned automatically. Status defaults to UNKNOWN if not provided."
      operationId: createDevice
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DeviceInput'
      responses:
        '201':
          description: "Device created"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Device'

  /api/devices/{id}:
    get:
      summary: "Get device by ID"
      operationId: getDevice
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
          description: "Device unique identifier"
      responses:
        '200':
          description: "Device found"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Device'
        '404':
          description: "Device not found"

  /api/devices/search:
    get:
      summary: "Search devices"
      description: "Full-text search across device fields. Returns paginated results."
      operationId: searchDevices
      parameters:
        - name: q
          in: query
          required: true
          schema:
            type: string
          description: "Search query string"
        - name: page
          in: query
          required: false
          schema:
            type: integer
            default: 0
          description: "Page number (zero-based)"
        - name: size
          in: query
          required: false
          schema:
            type: integer
            default: 20
          description: "Page size"
      responses:
        '200':
          description: "Paginated search results"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PaginatedDeviceResponse'

components:
  schemas:
    Device:
      type: object
      properties:
        id:
          type: string
          description: "Unique identifier (UUID)"
        name:
          type: string
          description: "Device display name"
        ipAddress:
          type: string
          description: "Device IP address"
        macAddress:
          type: string
          description: "Device MAC address"
        status:
          $ref: '#/components/schemas/DeviceStatus'
        lastSeen:
          type: string
          format: date-time
          description: "Timestamp of when the device was last seen"
        plugins:
          type: array
          items:
            $ref: '#/components/schemas/Plugin'
          description: "Network protocol plugins associated with this device"
      required:
        - id

    DeviceInput:
      type: object
      description: "Payload for creating a new device (id is auto-generated)"
      properties:
        name:
          type: string
          description: "Device display name"
        ipAddress:
          type: string
          description: "Device IP address"
        macAddress:
          type: string
          description: "Device MAC address"
        status:
          $ref: '#/components/schemas/DeviceStatus'

    Plugin:
      type: object
      properties:
        id:
          type: string
          description: "Unique plugin identifier"
        name:
          type: string
          description: "Display name of the plugin (e.g. 'SNMP v3')"
        protocol:
          $ref: '#/components/schemas/PluginProtocol'
        version:
          type: string
          description: "Plugin version"
        enabled:
          type: boolean
          description: "Whether the plugin is enabled"
      required:
        - id
        - name
        - protocol

    PluginProtocol:
      type: string
      enum:
        - SNMP
        - NETCONF
        - SSH
        - TELNET
        - HTTP
      description: "Network protocol type supported by a plugin"

    DeviceStatus:
      type: string
      enum:
        - ONLINE
        - OFFLINE
        - MAINTENANCE
        - UNKNOWN
      description: "Current operational status of a device"

    PaginatedDeviceResponse:
      type: object
      properties:
        content:
          type: array
          items:
            $ref: '#/components/schemas/Device'
          description: "Devices on the current page"
        page:
          type: integer
          description: "Current page number (zero-based)"
        size:
          type: integer
          description: "Page size"
        totalElements:
          type: integer
          format: int64
          description: "Total number of matching devices"
        totalPages:
          type: integer
          description: "Total number of pages"
        first:
          type: boolean
          description: "Whether this is the first page"
        last:
          type: boolean
          description: "Whether this is the last page"
      required:
        - content
        - page
        - size
        - totalElements
        - totalPages
